sudo: false
language: python
python:
  - "2.7"
before_script:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
  - pip install pycodestyle
  - npm install -g jshint
  - cp travis-ci/manage.py manage.py
script:
  - pycodestyle --exclude=migrations nagios_registration/
  - jshint nagios_registration/static/js --verbose
  - coverage run --include=nagios_registration/* manage.py test nagios_registration
after_success:
  - coveralls
